### ISSUE TITLE
Why is Playify not two-way?

### ISSUE THREAD

**Issue by matteyas** [krmax44/Playify#14]
This is not an issue so much as a feature suggestion.

My friends post links in Spotify, and I'd love to be able to open them directly in the Google player; Playify does this from what I can tell.

What if I want to share a song from Play Music to my friends who use Spotify though? :)

Preferably, in my use case, I'd just convert the song I'm sharing to a Spotify search url, but of course, it would be okay if I could just tell my friends to install Playify and I could share the song url directly.

Maybe there are online link converters available, I haven't looked thoroughly, suggestions welcome!

**Comment by krmax44** [comment]
That's because most streaming platforms don't have APIs. Spotify is an exception here, so I can take a Spotify URL, ask the API what track behind that URL is and forward that to any other streaming service. With let's say Amazon Music, I cannot look up whatever track is behind a URL, at least not in a way that is elegant or legal.

A dedicated sharing platform could fix this, but I don't see many users interested in something like that.

**Comment by matteyas** [comment]
Okay I see! There are unofficial APIs for Play Music. Maybe I'll just fork this extension and add it for myself if you don't feel comfortable with an unofficial API (makes very much sense for public projects!).

Oh, here's a share link from Play Music: https://play.google.com/music/m/Th3jpztylqbityczm6w73foly5u?t=Not_Today_-_Chill_Bump

Artist and song after t=, I'll just make an AHK script for it :)
